name: instagram_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.1
  redux: ^4.0.0
  flutter_redux: ^0.6.0
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^0.13.6
  intl: ^0.16.1
  email_validator: ^1.0.4
  password_strength: ^0.1.2
  built_value: ^7.1.0
  built_collection: ^4.3.2
  camera: ^0.5.8+2
  path_provider: ^1.6.10
  uuid: ^2.0.4
  firebase_storage: ^3.1.6
  firebase_messaging: ^6.0.16
  redux_epics: ^0.14.0
  rxdart: ^0.24.1
  timeago: ^2.0.26
  algolia: ^0.1.7
  cloud_functions: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  built_value_generator: ^7.1.0

flutter:
  uses-material-design: true
  assets:
    - res/logo.png
    - res/instagram_cake.png